project:
  name: quickstart-hail
  regions:
    - us-east-1
  parameters:
      pKmsEbsArn: ''
      pS3packerZipLocation: ami/packer.zip
      pHailBucket: hail-$[taskcat_autobucket]
      pSageMakerBucket: sg-$[taskcat_autobucket]
      pSubnetType: private
      pTagOwner: ''
      pTagEnvironment: development
      pCreateHailBucket: "yes"
      pCreateSageMakerBucket: "yes"
      QSS3BucketName: $[taskcat_autobucket]

tests:
  vpcNew:
    parameters:
      pTargetVpc: new
      pNewVpcCidr: 10.0.0.0/16
      pVpcId: ''
      pSubnetId: ''
      pSubnetType: private
    template: ./templates/hail-master.yml
