AWSTemplateFormatVersion: "2010-09-09"
Description: "SageMaker Notebook Instance for use with Hail on EMR"

Parameters:

  pAllowSsmShell:
    AllowedValues:
      - "false"
      - "true"
    Default: "false"
    Description: "Allow Systems Manager (SSM) shell access to EMR nodes.  Must also be set to true on EMR CloudFormation stacks."
    Type: "String"

  pInstanceType:
    AllowedValues:
      - "ml.t2.medium"
      - "ml.t2.large"
      - "ml.t2.xlarge"
      - "ml.t2.2xlarge"
      - "ml.t3.medium"
      - "ml.t3.large"
      - "ml.t3.xlarge"
      - "ml.t3.2large"
    Default: "ml.t3.medium"
    Description: ""
    Type: "String"

  pName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    Description: "Used as the name of the notebook instance and S3 backup location.  Username is recommend - E.g. jsmith"
    Type: "String"

  pSageMakerBucket:
    Description: "This parameter is set by the S3 stack.  No changes should be necessary.  S3 bucket with scripts, common notebooks, and home directory backups."
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/hail/s3/sagemaker"

  pHailBucket:
    Description: "This parameter is set by the S3 stack.  No changes should be necessary.  Notebook instance will have full read."
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/hail/s3/hail"

  pSubnetId:
    Description: "This parameter is set by the hail-core stack. No changes should be necessary."
    Default: "/hail/vpc/subnet-id"
    Type: "AWS::SSM::Parameter::Value<String>"

  pSubnetType:
    Description: "This parameter is set by the hail-core stack. No changes should be necessary."
    Default: "/hail/vpc/subnet-type"
    Type: "AWS::SSM::Parameter::Value<String>"

  pTagEnvironment:
    AllowedValues:
      - "production"
      - "staging"
      - "development"
    Default: "development"
    Description: "Environment type for default resource tagging."
    Type: "String"

  pTagOwner:
    Default: ""
    Description: "(Optional) Owner of the resources.  Person/Department, etc."
    Type: "String"

  pVolumeSize:
    Default: "20"
    Description: "Size (GB)."
    MaxValue: "500"
    MinValue: "5"
    Type: "Number"

  pSgSagemaker:
    Description: "This parameter is set by the hail-core stack.  No changes should be necessary.  This security group ID will be attached to the notebook instance."
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/hail/sagemaker/security-group-id"


Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Network Details"
        Parameters:
          - "pSubnetId"
          - "pSubnetType"
          - "pSgSagemaker"
      - Label:
          default: "Instance Details"
        Parameters:
          - "pName"
          - "pInstanceType"
          - "pVolumeSize"
          - "pAllowSsmShell"
      - Label:
          default: "S3 Resources"
        Parameters:
          - "pHailBucket"
          - "pSageMakerBucket"
      - Label:
          default: "Tagging"
        Parameters:
          - "pTagEnvironment"
          - "pTagOwner"
    ParameterLabels:
      pAllowSsmShell:
        default: "Allow SSM Shell Access to EMR Nodes"
      pSubnetId:
        default: "SSM Parameter for Subnet ID"
      pSubnetType:
        default: "SSM Parameter for Subnet Type"
      pName:
        default: "Instance Name"
      pInstanceType:
        default: "Instance Type"
      pVolumeSize:
        default: "Volume Size"
      pHailBucket:
        default: "SSM Parameter for Hail Bucket"
      pSageMakerBucket:
        default: "SSM Parameter for SageMaker Bucket"
      pSgSagemaker:
        default: "SSM Parameter for SageMaker Security Group ID"
      pTagOwner:
        default: "Owner"
      pTagEnvironment:
        default: "Environment"

Conditions:

  CondAllowSsmShell: !Equals [!Ref pAllowSsmShell, "true"]
  CondSubnetTypePrivate: !Equals [!Ref pSubnetType, "private"]

Resources:

  instance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      DirectInternetAccess: !If [ CondSubnetTypePrivate, "Disabled", "Enabled"]
      InstanceType: !Ref pInstanceType
      RoleArn: !GetAtt role.Arn
      LifecycleConfigName: !GetAtt lifecycleConfiguration.NotebookInstanceLifecycleConfigName
      NotebookInstanceName: !Ref pName
      RootAccess: Enabled
      SubnetId: !Ref pSubnetId
      VolumeSizeInGB: !Ref pVolumeSize
      SecurityGroupIds:
        - !Ref pSgSagemaker
      Tags:
        - Key: "Name"
          Value: !Ref pName
        - Key: "environment"
          Value: !Ref pTagEnvironment
        - Key: "owner"
          Value: !Ref pTagOwner

  lifecycleConfiguration:
    Type: "AWS::SageMaker::NotebookInstanceLifecycleConfig"
    Properties:
      NotebookInstanceLifecycleConfigName: !Sub "${pName}"
      OnCreate:
        - Content:
            Fn::Base64: !Sub |
              #!/bin/bash
              set -ex

              BUCKET="${pSageMakerBucket}"
              EC2_USER_BIN="/home/ec2-user/SageMaker/bin/"
              sudo -u ec2-user -i <<EOF
              set -ex
              /usr/bin/aws s3 cp s3://"$BUCKET"/scripts/ "$EC2_USER_BIN" --recursive
              find "$EC2_USER_BIN" -type f -exec chmod -v 700 {} \;
              EOF
      OnStart:
        - Content:
            Fn::Base64: !Sub |
              #!/bin/bash
              set -ex

              BUCKET="${pSageMakerBucket}"
              DIRECTORY="/home/ec2-user/SageMaker/"

              # Copy previously backed up user notebooks
              /usr/bin/aws s3 cp s3://$BUCKET/${pName}/ $DIRECTORY --recursive
              # Reset bin permissions
              find "$DIRECTORY/bin/" -type f -exec chmod -v 700 {} \;
              # Copy common organization notebooks.  This will overwrite common notebooks previously saved to the home directory
              /usr/bin/aws s3 cp s3://$BUCKET/common-notebooks/ $DIRECTORY/common-notebooks/ --recursive
              # sudo chown "ec2-user":"ec2-user" $DIRECTORY --recursive

              # Use the system AWS, since ec2-user may change conda environments
              CMD="/usr/bin/aws s3 sync --exclude 'bin/*' --exclude '.sparkmagic/*' --exclude '*.ipynb_checkpoints/*' $DIRECTORY s3://$BUCKET/${pName}/ > /home/ec2-user/s3-backup.log 2>&1"
              chown "ec2-user":"ec2-user" $DIRECTORY --recursive
              # Backup the notebook details to S3 on 5 minute intervals
              cronjob="*/5 * * * * $CMD"
              echo "$cronjob" | crontab -u "ec2-user" -

              # Conda/Pip additions
              sudo -u ec2-user -i <<EOF
              source /home/ec2-user/anaconda3/bin/activate JupyterSystemEnv
              # Required for "%manage_spark"
              jupyter labextension install @jupyter-widgets/jupyterlab-manager
              source /home/ec2-user/anaconda3/bin/deactivate

              # Prevent iopub throttling
              sed -i.bak 's/^#c.NotebookApp.iopub_data_rate_limit.*$/c.NotebookApp.iopub_data_rate_limit = 1000000/' ~/.jupyter/jupyter_notebook_config.py
              # Session Manager for SSM connections to EMR nodes, if desired.
              sudo yum -y install https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm
              EOF

  role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "sagemaker.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "s3FullUserPathControl"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "s3:*"
                Resource:
                  - !Sub "arn:aws:s3:::${pSageMakerBucket}/${pName}/*"
              - Effect: "Allow"
                Action:
                  - "s3:ListObject"
                  - "s3:ListBucket"
                Resource: !Sub "arn:aws:s3:::${pSageMakerBucket}"
        - PolicyName: "s3ListPaths"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "s3:ListBucket"
                Resource:
                  - !Sub "arn:aws:s3:::${pSageMakerBucket}"
                Condition:
                  StringLike:
                    s3:prefix:
                      - !Sub "${pName}/"
                      - "scripts/"
                      - "common-notebooks/"
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                Resource:
                  - !Sub "arn:aws:s3:::${pSageMakerBucket}/scripts/*"
                  - !Sub "arn:aws:s3:::${pSageMakerBucket}/common-notebooks/*"
        - PolicyName: "s3hailFullRead"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:Get*"
                  - "s3:List*"
                Resource:
                  - !Sub "arn:aws:s3:::${pHailBucket}/*"
                  - !Sub "arn:aws:s3:::${pHailBucket}"
        - PolicyName: "cloudwatchWrite"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogStream"
                  - "logs:CreateLogGroup"
                  - "logs:PutLogEvents"
                Resource: "*"
        - PolicyName: "emrListClusters"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "elasticmapreduce:ListInstances"
                  - "elasticmapreduce:ListBootstrapActions"
                  - "elasticmapreduce:ListClusters"
                  - "elasticmapreduce:DescribeCluster"
                  - "elasticmapreduce:ListInstanceGroups"
                Resource: "*"
      RoleName: !Sub "sagemaker-${pName}"

  policyAllowSsmShell:
    Type: "AWS::IAM::Policy"
    Condition: "CondAllowSsmShell"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ssm:StartSession"
            Resource: "arn:aws:ec2:*:*:instance/*"
            Condition:
              StringLike:
                "ssm:resourceTag/allow-emr-ssm":
                  - "true"
      PolicyName: "ssm-session-by-tag"
      Roles:
        - !Ref role

Outputs:

  url:
    Description: "Console Notebook URL"
    Value: !Sub "https://console.aws.amazon.com/sagemaker/home?region=${AWS::Region}#/notebook-instances/${pName}"
