AWSTemplateFormatVersion: "2010-09-09"
Description: "Service Catalog Portfolio containing products for a Hail EMR cluster and SageMaker Jupyter Notebook instance."

Parameters:

  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: "aws-quickstart"
    Description: "S3 bucket name for the Quick Start assets. Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: "String"

  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: "quickstart-aws-hail/"
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: "String"

Resources:

  Portfolio:
    Type: "AWS::ServiceCatalog::Portfolio"
    Properties:
      Description: "Hail EMR and SageMaker Notebook Offerings"
      DisplayName: "Hail Products"
      ProviderName: "AWS"

  ProductEmr:
    Type: "AWS::ServiceCatalog::CloudFormationProduct"
    Properties:
      Description: "Hail EMR Cluster"
      Name: "Hail EMR Cluster"
      Owner: "AWS"
      ProvisioningArtifactParameters:
        - Info:
            LoadTemplateFromURL: !Sub "https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/hail-emr.yml"

  AssociationEmr:
    Type: "AWS::ServiceCatalog::PortfolioProductAssociation"
    Properties:
      PortfolioId: !Ref Portfolio
      ProductId: !Ref ProductEmr

  ProductSageMakerNotebook:
    Type: "AWS::ServiceCatalog::CloudFormationProduct"
    Properties:
      Description: "SageMaker Notebook Instance"
      Name: "Hail SageMaker Notebook Instance"
      Owner: "AWS"
      ProvisioningArtifactParameters:
        - Info:
            LoadTemplateFromURL: !Sub "https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/hail-jupyter.yml"

  AssociationSageMakerNotebook:
    Type: "AWS::ServiceCatalog::PortfolioProductAssociation"
    Properties:
      PortfolioId: !Ref Portfolio
      ProductId: !Ref ProductSageMakerNotebook