AWSTemplateFormatVersion: "2010-09-09"
Description: "Hail S3, AMI, and Service Catalog Stacks"

Parameters:

  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: "aws-quickstart"
    Description: "S3 bucket name for the Quick Start assets. Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: "String"

  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: "quickstart-aws-hail/"
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: "String"

  pHailBucket:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    Description: "Required - Contains cache, bootstrapping, etc.  S3-SSE encryption at rest."
    Type: "String"

  pKmsEbsArn:
    Description: "Optional - if the source AMI is encrypted specify the full key ARN.  Otherwise, leave blank.  This does NOT automatically enable EBS encryption."
    Default: ""
    Type: "String"

  pLogBucket:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    Description: "Required - Will use S3-SSE encryption at rest."
    Type: "String"

  pS3packerZipLocation:
    Default: "ami/packer.zip"
    Description: "Required - S3 Key where you will upload the Packer Zip for new AMI builds in the Hail Bucket."
    Type: "String"

  pSageMakerBucket:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    Description: "Required - SageMaker Jupyter home directories will be sync'd here.  S3-SSE encryption at rest."
    Type: "String"

  pTagEnvironment:
    AllowedValues:
      - "production"
      - "staging"
      - "sandbox"
      - "test"
      - "development"
      - "qa"
      - "dr"
    Default: "development"
    Description: "Optional - Environment type for default resource tagging."
    Type: "String"

  pTagOwner:
    Type: "String"
    Description: "Optional - Owner of the resources.  Person/Department, etc."
    Default: ""

  pSubnetId:
    Description: "Required for existing VPC target. Subnet for EMR Cluster and SageMaker Notebook Instances.  Must reside in the existing VPC."
    Type: "AWS::EC2::Subnet::Id"

  pSubnetType:
    Description: "Required for existing VPC target. Public subnets deploy resources with public IPs.  Private subnets do not.  Private subnets are recommended."
    Type: "String"
    AllowedValues:
      - "public"
      - "private"
    Default: "private"

  pVpcId:
    Description: "Required - SageMaker security group is created in this VPC."
    Type: "AWS::EC2::VPC::Id"

Resources:

  stackS3:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/hail-s3.yml"
      Parameters:
        pHailBucket: !Ref pHailBucket
        pLogBucket: !Ref pLogBucket
        pSageMakerBucket: !Ref pSageMakerBucket
        pTagEnvironment: !Ref pTagEnvironment
        pTagOwner: !Ref pTagOwner
      TimeoutInMinutes: 5

  stackAmi:
    DependsOn:
      - stackS3
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/hail-ami.yml"
      Parameters:
        pKmsEbsArn: !Ref pKmsEbsArn
        pS3bucketHail: !Ref pHailBucket
        pS3bucketRodaHail: !GetAtt rodaBucketParameter.Value
        pS3packerZipLocation: !Ref pS3packerZipLocation
        pSubnetId: !Ref pSubnetId
        pVpcId: !Ref pVpcId
      TimeoutInMinutes: 5

  stackServiceCatalog:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/hail-service-catalog.yml"
      Parameters:
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
      TimeoutInMinutes: 5

  sgSagemaker:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: !Ref pVpcId
      GroupDescription: "Security group for SageMaker Notebook instances to connect to Hail clusters."
      SecurityGroupEgress:
        - IpProtocol: "-1"
          FromPort: -1
          ToPort: -1
          CidrIp: "0.0.0.0/0"
          Description: "all"
      Tags:
        - Key: "environment"
          Value: !Ref pTagEnvironment
        - Key: "owner"
          Value: !Ref pTagOwner

  sagemakerSgParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "Security Group ID to attach to Hail SageMaker notebook instances."
      Name: "/hail/sagemaker/security-group-id"
      Type: "String"
      Value: !Ref sgSagemaker

  subnetIdParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "Target subnet for Hail EMR cluster and SageMaker notebook instances."
      Name: "/hail/vpc/subnet-id"
      Type: "String"
      Value: !Ref pSubnetId

  vpcIdParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "Target VPC for Hail EMR cluster and SageMaker notebook instances."
      Name: "/hail/vpc/id"
      Type: "String"
      Value: !Ref pVpcId

  subnetTypeParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "Subnet type, public or private, for Hail resources.  Drives SageMaker notebook networking configuration."
      Name: "/hail/vpc/subnet-type"
      Type: "String"
      Value: !Ref pSubnetType

  roleLambdaS3seed:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "cloudwatch-log-write"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Resource: "arn:aws:logs:*:*:*"
              Effect: "Allow"
        - PolicyName: "sagemaker-s3-put-object"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              Action:
                - "s3:PutObject"
              Resource:
                - !Sub "arn:aws:s3:::${pSageMakerBucket}/common-notebooks/*"
                - !Sub "arn:aws:s3:::${pSageMakerBucket}/scripts/*"
              Effect: "Allow"
        - PolicyName: "s3-quickstart-list"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              Action:
                - "s3:ListBucket"
              Resource:
                - !Sub "arn:aws:s3:::${QSS3BucketName}"
              Effect: "Allow"
        - PolicyName: "s3-quickstart-get-object"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              Action:
                - "s3:GetObject"
              Resource:
                - !Sub "arn:aws:s3:::${QSS3BucketName}/*"
              Effect: "Allow"
      RoleName: "hail-s3-lambda"

  lambdaS3seed:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "index.lambda_handler"
      Role: !GetAtt roleLambdaS3seed.Arn
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import os

          client = boto3.client("s3")


          def sync_path(source_bucket, dest_bucket, source_prefix, dest_prefix):
              for obj in client.list_objects_v2(Bucket=source_bucket, Prefix=source_prefix)[
                  "Contents"
              ]:
                  source_file = obj["Key"]

                  # Omit "directories" from copy
                  if not source_file.endswith("/"):
                      dest_filename = os.path.split(source_file)[1]
                      print(
                          f"Copy s3://{source_bucket}/{source_file} => s3://{dest_bucket}/{dest_prefix}{dest_filename}"
                      )

                      client.copy_object(
                          Bucket=dest_bucket,
                          Key=dest_prefix + dest_filename,
                          CopySource=source_bucket + "/" + source_file,
                      )


          def lambda_handler(event, context):
              print(event)
              try:
                  source_bucket = event["ResourceProperties"]["QSS3BucketName"]
                  dest_bucket = event["ResourceProperties"]["SageMakerBucketName"]
                  quickstart_prefix = event["ResourceProperties"]["QSS3KeyPrefix"] + "sagemaker/"

                  if event["RequestType"] in ["Create", "Update"]:
                      print(f'{event["RequestType"]} Request by CFN...')
                      source_paths = ["scripts/", "common-notebooks/"]
                      for path in source_paths:
                          sync_path(source_bucket, dest_bucket, quickstart_prefix + path, path)
                      rdata = {"Status": "SUCCESS"}
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, rdata)
                  elif event["RequestType"] == "Delete":
                      print("Delete Request by CFN...")
                      rdata = {"Status": "Success"}
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, rdata)
              except Error as e:
                  print("[ERROR] - %s" % str(e))
                  rdata = {"Error": "Could not perform the operation"}
                  cfnresponse.send(event, context, cfnresponse.FAILED, rdata)

      Runtime: "python3.7"
      Timeout: 300

  lambdaS3seedPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      Principal: "cloudformation.amazonaws.com"
      FunctionName: !GetAtt lambdaS3seed.Arn

  lambdaS3seedInvoke:
    Type: "Custom::InvokeLambdaFunction"
    Properties:
      QSS3BucketName: !Ref QSS3BucketName
      QSS3KeyPrefix: !Ref QSS3KeyPrefix
      SageMakerBucketName: !Ref pSageMakerBucket
      ServiceToken: !GetAtt lambdaS3seed.Arn

  rodaBucketParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Description: "Registry of Open Data Hail S3 Bucket.  Contains VEP and LOFTEE data."
      Name: "/hail/s3/roda"
      Type: "String"
      Value: "hail-vep-pipeline"
